### ISSUE TITLE
Invalid function name in the documentation

### ISSUE THREAD

**Issue by blockchain-doppelganger** [devery/deveryjs#1]
https://devery.github.io/deveryjs/DeveryRegistry.html#getBrand

In example of code usage, line 4, must be deveryRegistryClient.getBrand() instead of deveryRegistryClient.getApp

**Comment by victorrseloy** [comment]
Thanks for bringing this to your attention. I will fix the docs.

**Comment by victorrseloy** [comment]
fixed on commit d960cf46ba46074fc140978b878499f1a91a53a8
