### ISSUE TITLE
You should create proxy-contract

### ISSUE THREAD

**Issue by blockchain-doppelganger** [devery/deveryjs#2]
Why you didn't write proxy-contract ? I see a few changes that you can do to improve your product, but if deploy new contract all old data will be lost. I think you should create proxy-contract untill to many people use deveryjs

**Comment by andrewrd** [comment]
In terms of a data support, using our JS framework with our current contract will continue to support the deployed contract even in the case of future iterations. However this suggestion as mentioned before will be taken into consideration as proxy-contract standards are constantly emerging and with such come [vulnerabilities due to the nature of Solidity code.](https://medium.com/nomic-labs-blog/malicious-backdoors-in-ethereum-proxies-62629adf3357) Which pattern are you looking at specifically?

**Comment by blockchain-doppelganger** [comment]
I mean the pattern that is in this article, and if you read this carefully, you can watch that just you need is to add modifier "onlyProxyOwner" for a callback function.
you also can test  all contract function and find clashes if they exist (and just rename function)
I think upgradability is more important in this situation 

> In terms of a data support, using our JS framework with our current contract will continue to support the deployed contract even in the case of future iterations. However this suggestion as mentioned before will be taken into consideration as proxy-contract standards are constantly emerging and with such come [vulnerabilities due to the nature of Solidity code.](https://medium.com/nomic-labs-blog/malicious-backdoors-in-ethereum-proxies-62629adf3357) Which pattern are you looking at specifically?

**Comment by andrewrd** [comment]
The article refers to the OpenZeppelin proxy patterns of which there are multiple; inherited storage
eternal storage, unstructured Storage among others. Each has their respective benefits and tradeoffs, however future extensibility in this case of DeveryJS isn't entirely restricted to the contract layer and can be placed within the Javascript layer. 

Nonetheless we have taken this into consideration, and will also be soon issuing a new issue structure. This allow more efficient tracking of suggestions and extensions of the framework and allow community members such as yourself to participate directly into the direction of the framework.

**Comment by andrewrd** [comment]
I'll be locking this thread for the moment until the new structure is posted and determined.
