### ISSUE TITLE
where to buy EVE to power protocol

### ISSUE THREAD

**Issue by track-shaq** [devery/deveryjs#30]
Hi Team,

Where can the EVE token be purchased to pay for protocol functions? Not after a huge amount at this stage as we are only wanting to test the Devery protocol.

Shaq

**Comment by TruStlessP** [comment]
https://afmu.net/how-to-buy-devery-eve/

**Comment by markibanez** [comment]
Is there a way to get EVE on test networks like Ropsten?

**Comment by victorrseloy** [comment]
hi @markibanez , you can go to this address https://ropsten.etherscan.io/address/0x8aabe7eb19bc078dbf8d33cdcd1c1aa58fdb312b#writeContract and call the getAirdrop method. Every time you do this you will get 100 EVE on ropsten
