### ISSUE TITLE
DeveryRegistry.getBrandData returns error

### ISSUE THREAD

**Issue by markibanez** [devery/deveryjs#32]
I'm calling `getBrandData` method as follows

```
let registry = new DeveryRegistry();
const brandData = await registry.getBrandData(this.props.address);
console.log(brandData);
```

It results in the following error 
![image](https://user-images.githubusercontent.com/7534847/112640956-dd9bdb80-8e7c-11eb-8810-f197153ac857.png)

Calling `check` method I think works but also returns "MetaMask no longer injects web3" error but also returns an object. 

The following code:

```
let registry = new DeveryRegistry();
const brandData = await registry.check(this.props.address);
console.log(brandData);
```

Results into
![image](https://user-images.githubusercontent.com/7534847/112641305-37040a80-8e7d-11eb-97b4-32851e529a1b.png)

**Comment by markibanez** [comment]
I have resolved the issue by registering an application on the blockchain via addApp method

**Comment by victorrseloy** [comment]
Thanks for the input @markibanez, as you figured out it's necessary to register an app using the addApp method to use certain methods. Regarding the web3 error you have 2 options. 
Option 1: add ethers.js to your app, get window.ethereum and create a web3 provider and pass its signer as the web3 instance when instantiating the client.

```javascript
const provider = new ethers.providers.Web3Provider(window.ethereum);
const client = new DeveryRegistry({ web3Instance:provider.getSigner() })
```

option 2 add @metamask/legacy-web3 as a dependency to your project and pass window.web3  as the web3Instance

```javascript
 const client = new DeveryRegistry({ web3Instance:window.web3 })
```

**Comment by markibanez** [comment]
Thanks @victorrseloy

**Comment by markibanez** [comment]
Hi @victorrseloy 

I tried the first solution since I already had ethers.js in our project. Unfortunately it broke our react app. Pasting the error below

```
Error: invalid signer or provider (arg="signerOrProvider", value={"_isSigner":true,"provider":{"_isProvider":true,"_events":[],"_emitted":{"block":-2},"formatter":{"formats":{"transaction":{},"transactionRequest":{},"receiptLog":{},"receipt":{},"block":{},"blockWithTransactions":{},"filter":{},"filterLog":{}}},"anyNetwork":false,"_networkPromise":{},"_maxInternalBlockNumber":-1024,"_lastBlockNumber":-2,"_pollingInterval":4000,"_fastQueryDate":0,"connection":{"url":"metamask"},"_nextId":42,"provider":{"_events":{},"_eventsCount":1,"_maxListeners":100,"_log":{"levels":{"TRACE":0,"DEBUG":1,"INFO":2,"WARN":3,"ERROR":4,"SILENT":5}},"isMetaMask":true,"_state":{"sentWarnings":{"enable":false,"experimentalMethods":true,"send":false,"events":{"close":false,"data":false,"networkChanged":false,"notification":false}},"accounts":["0x68d99e952cf3d4faaa6411c1953979f54552a8f7"],"isConnected":true,"isUnlocked":true,"initialized":true,"isPermanentlyDisconnected":false},"_metamask":{},"selectedAddress":"0x68d99e952cf3d4faaa6411c1953979f54552a8f7","networkVersion":"3","chainId":"0x3","_rpcEngine":{"_events":{},"_eventsCount":0,"_middleware":[null,null,null]}}},"_index":0,"_address":null}, version=4.0.37)
```
