### ISSUE TITLE
EVE token

### ISSUE THREAD

**Issue by nouveaucode-jordan** [devery/deveryjs#34]
Hi team, where can one buy EVE tokens? Hotbit is down which is preventing us from continuing our development. Could we please decentralize this process and add some liquidity to uniswap, the current reliance on hotbit is not ideal

**Comment by victorrseloy** [comment]
Hi @nouveaucode-jordan, we don't discuss buying/selling or tokenomics on this repo. As this is not tech related I'm closing this issue.

**Comment by nouveaucode-jordan** [comment]
@victorrseloy my apologies - where is the appropriate forum for this discussion?
